### ISSUE TITLE
Image size growth

### ISSUE THREAD

**Issue by evmin** [zulu-openjdk/zulu-openjdk#12]
Image size has doubled between 8u131-8.21.0.1 and 8u144-8.23.0.3 versions.
Plus the latter one no longer contains /sbin/apk.

```
azul/zulu-openjdk-alpine                                             8u144-8.23.0.3      f6e73b1499cd        4 weeks ago         358MB
azul/zulu-openjdk-alpine                                             8u131-8.21.0.1      1b1b5f2ff899        3 months ago        189MB
```

Am I missing something obvious here?

P.S. Thank you for the great work with maintaining the images - this is priceless.

**Comment by sgrinev** [comment]
There were no changes in Dockerfile except the binary name, we'll look into that, thanks for reporting.

**Comment by cazacugmihai** [comment]
Are there any updates on this issue? Thanks!

**Comment by isenberg** [comment]
Here an overview of the current docker image sizes.

If you need Zulu 8u144-8.23.0.3 in a small image, then use the image with tag "8" instead of tag "8u144". Note, that using the tag "latest" might later change to Java 9.

root@ubuntu16:~# docker pull azul/zulu-openjdk-alpine:8u131
root@ubuntu16:~# docker pull azul/zulu-openjdk-alpine:8u144 
root@ubuntu16:~# docker pull azul/zulu-openjdk-alpine:8
root@ubuntu16:~# docker pull azul/zulu-openjdk-alpine:latest

root@ubuntu16:~# docker images
REPOSITORY                TAG                IMAGE ID            CREATED            SIZE
azul/zulu-openjdk-alpine  8u131        261a4ee0aa37        4 months ago      189MB
azul/zulu-openjdk-alpine  8u144       1011406ebf27          2 months ago      358MB
azul/zulu-openjdk-alpine  8                e73e0f440aab        8 weeks ago        189MB
azul/zulu-openjdk-alpine  latest         660934c998dd      8 weeks ago        189MB

root@ubuntu16:~# docker run -it --rm azul/zulu-openjdk-alpine:8 java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (Zulu 8.23.0.3-linux64) (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (Zulu 8.23.0.3-linux64) (build 25.144-b01, mixed mode)

root@ubuntu16:~# docker run -it --rm azul/zulu-openjdk-alpine:8u144 java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (Zulu 8.23.0.3-linux64) (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (Zulu 8.23.0.3-linux64) (build 25.144-b01, mixed mode)

**Comment by isenberg** [comment]
Please note that this thread about the increase image size is only related to the the Zulu Alpine Linux Docker Image from the following sources:
https://hub.docker.com/r/azul/zulu-openjdk-alpine
https://github.com/zulu-openjdk/zulu-openjdk/tree/master/alpine

It's not about the Zulu Ubuntu Docker Image from the following sources:
https://hub.docker.com/r/azul/zulu-openjdk/
https://github.com/zulu-openjdk/zulu-openjdk

**Comment by sgrinev** [comment]
This issue have been fixed: https://hub.docker.com/r/azul/zulu-openjdk-alpine/tags/ 
Sorry for a long delay.
