### ISSUE TITLE
arm64 arch not longer available for 17.0.2-jre image on Docker Hub

### ISSUE THREAD

**Issue by devoto13** [zulu-openjdk/zulu-openjdk#152]
Couple of weeks ago [`azul/zulu-openjdk-alpine:17.0.2-jre` tag](https://hub.docker.com/r/azul/zulu-openjdk-alpine/tags?page=1&name=17.0.2-jre) on Docker Hub was a multi arch manifest providing both `amd64` and `arm64` variants. However, now this tag only has `amd64` architecture. Is it a bug? Or was it intentionally removed? I can see that there are still [`arm64` images available](https://hub.docker.com/r/azul/zulu-openjdk-alpine/tags?page=1&name=17.0.2), but the main manifest does not seem to include them for some reason.

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/823594/178258885-c3048f11-7177-42b0-bbd0-5dd843dfec12.png">

**Comment by rohit-tandon** [comment]
Piggybacking here but I have same issue with `azul/zulu-openjdk-alpine:17.0.2` tag, it no longer has `arm64` arch
![Screenshot 2022-07-14 at 10 06 57](https://user-images.githubusercontent.com/20339489/178933858-494e4c35-c4e3-4f7a-9dd6-df3a9257732c.png)
.

**Comment by wallind** [comment]
I was tasked recently with using Renovate to manage our usage of the [azul/zulu-openjdk:17-jre-headless](https://hub.docker.com/r/azul/zulu-openjdk/tags?page=1&name=17-jre-headless) in our CI/CD process and ran into this.

Similarly I had been looking at previous copies of the tag which had both `arm64` and `amd64` while doing research and building up my understanding.

Then this week I went to check it out on Docker Hub and noticed that only the `amd64` one was present. This was very confusing/damaging to my mental model of how things were working and I just couldn't wrap my head around it.

Then later this week the `arm64` one showed up. See their creation dates below (gather using `docker inspect` which illustrate the lapse where one existed and the other didn't.

- `azul/zulu-openjdk:17-jre-headless@sha256:f74e97e43ba0e210c27f07e340f1c38d51f3a724165dc4c88b27f1ac6c91b973`: `2022-07-11T18:33:14.813713514Z`
- `azul/zulu-openjdk:17-jre-headless@sha256:05714fb39f4f39c66e6dcc1614d7502c26f7af038c52f1d8db5645b4ab2fe6a5`: `2022-07-15T06:43:43.352542068Z`

I'm not gonna even try to comment on the correctness/incorrectness of that gap because my understanding of the generative systems behind these images just isn't that deep yet. However I would `NOTE:` this seems to be related to https://github.com/zulu-openjdk/zulu-openjdk/issues/145, https://github.com/zulu-openjdk/zulu-openjdk/issues/142, and https://github.com/zulu-openjdk/zulu-openjdk/issues/132. Notably the dev team seems to acknowledge that this is unexpected here https://github.com/zulu-openjdk/zulu-openjdk/issues/132#issuecomment-1074057618.

However I might add that I think the solution to insulate yourself from a misstep(allegedly) like this is to specify your dependency on a specific Digest as opposed to just the tag. Because even if the current Manifest the Tag points to doesn't have your desired architecture the Digest you currently point to will still exist on the registry. See here for some explanation of the Digest level https://hackernoon.com/docker-images-name-vs-tag-vs-digest

*granted I am extremely new to some of the in-depth mechanics of Docker (like as of this week)

**Comment by it-mak** [comment]
17.0.2-jre already has multiarch
