### ISSUE TITLE
Hash Sum mismatch?

### ISSUE THREAD

**Issue by hecong-cac** [zulu-openjdk/zulu-openjdk#156]
I am getting this error when trying to update:
```
#0 17.27 Get:20 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted arm64 Packages [4,330 B]
#0 17.45 Get:21 http://ports.ubuntu.com/ubuntu-ports focal-security/main arm64 Packages [1,419 kB]
#0 18.14 Fetched 18.8 MB in 17s (1,090 kB/s)
#0 18.14 Reading package lists...
#0 25.91 E: Failed to fetch https://repos.azul.com/zulu/deb/dists/stable/main/binary-arm64/by-hash/SHA512/9eba1e466100bb5171971a5c98361dd29ffec262b4213db403d7887b419f1ec0c29a5d5226f689b77e8a9e814d70922049f67bdd322074800838a038a8bf00e4  Hash Sum mismatch
#0 25.91    Hashes of expected file:
#0 25.91     - Filesize:63990 [weak]
#0 25.91     - SHA512:9eba1e466100bb5171971a5c98361dd29ffec262b4213db403d7887b419f1ec0c29a5d5226f689b77e8a9e814d70922049f67bdd322074800838a038a8bf00e4
#0 25.91     - SHA256:be230cd35b76b011c1821a7d65842bae4fed4f10720a4a32deacdc09f6cbf264
#0 25.91     - SHA1:ba6f8ef159ae99251cbd9ba18cf39909cc8d17ba [weak]
#0 25.91     - MD5Sum:0ebd7c45fc9edefa55552aab39cad802 [weak]
#0 25.91    Hashes of received file:
#0 25.91     - SHA512:e46fede753e23a536c224f276e5b768eff5f04fd77ac21c9b755d34a0e388c211bf13fb9b3101df78939368f79f9087184e6367630da511d9f9372b34316e6c7
#0 25.91     - SHA256:b059a60b16ca916e898799019049ef722c88edb123757d639b21c967d201d1f7
#0 25.91     - SHA1:f48bbcbf81fe3ebf35560e025f66c358384a83e3 [weak]
#0 25.91     - MD5Sum:ad7b51dbd54ebfbc6ad0f1c47b2b0bd8 [weak]
#0 25.91     - Filesize:485783 [weak]
#0 25.91    Last modification reported: Fri, 05 Aug 2022 12:54:22 +0000
#0 25.91    Release file created at: Fri, 05 Aug 2022 12:54:22 +0000
#0 25.91 E: Failed to fetch https://repos.azul.com/zulu/deb/dists/stable/main/binary-amd64/by-hash/SHA512/f568786bb6470e4a2d61af80741447c817e6ec8a2aa940f02637d790a2d5b893a2e6f6a529282353f42ca7d96d25a46a3f447fd27044f43a3c9da551c4a9045e  
#0 25.91 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
Dockerfile:4
--------------------
   
   4 | >>> RUN  apt-get update 
   5 |     RUN  apt-get -y upgrade
```

My Dockerfile
```
FROM azul/zulu-openjdk:8u345

RUN  apt-get update
RUN  apt-get -y upgrade

USER "root"
CMD ["echo ok"]
```
With command:`docker buildx build --platform linux/amd64,linux/arm64/v8 -t test.com/test.v1 .`

**Comment by DockerElla** [comment]
Hello,
We've also had this problem since last friday using stable/main of 17.0.4

`Get:10 https://repos.azul.com/zulu/deb stable/main arm64 Packages [64.0 kB]
Err:10 https://repos.azul.com/zulu/deb stable/main arm64 Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:63990 [weak]
   - SHA512:9eba1e466100bb5171971a5c98361dd29ffec262b4213db403d7887b419f1ec0c29a5d5226f689b77e8a9e814d70922049f67bdd322074800838a038a8bf00e4
   - SHA256:be230cd35b76b011c1821a7d65842bae4fed4f10720a4a32deacdc09f6cbf264
   - SHA1:ba6f8ef159ae99251cbd9ba18cf39909cc8d17ba [weak]
   - MD5Sum:0ebd7c45fc9edefa55552aab39cad802 [weak]
  Hashes of received file:
   - SHA512:e46fede753e23a536c224f276e5b768eff5f04fd77ac21c9b755d34a0e388c211bf13fb9b3101df78939368f79f9087184e6367630da511d9f9372b34316e6c7
   - SHA256:b059a60b16ca916e898799019049ef722c88edb123757d639b21c967d201d1f7
   - SHA1:f48bbcbf81fe3ebf35560e025f66c358384a83e3 [weak]
   - MD5Sum:ad7b51dbd54ebfbc6ad0f1c47b2b0bd8 [weak]
   - Filesize:485783 [weak]
  Last modification reported: Fri, 05 Aug 2022 12:54:22 +0000
  Release file created at: Fri, 05 Aug 2022 12:54:22 +0000`
  
  FROM azul/zulu-openjdk:17-jre

**Comment by AntonKozlov** [comment]
Thanks for reports. We are investigating the problem.

**Comment by it-mak** [comment]
Already fixed.
