### ISSUE TITLE
Vulnerability CVE-2023-0286 on azul/zulu-openjdk-alpine:17

### ISSUE THREAD

**Issue by emmanuelfreitas** [zulu-openjdk/zulu-openjdk#184]
[openssl: X.400 address type confusion in X.509 GeneralName]

OpenSSL versions 3.0, 1.1.1 and 1.0.2 are vulnerable to this issue.
OpenSSL 3.0 users should upgrade to OpenSSL 3.0.8.
OpenSSL 1.1.1 users should upgrade to OpenSSL 1.1.1t.
OpenSSL 1.0.2 users should upgrade to OpenSSL 1.0.2zg (premium support customers
only).
More details in: https://www.openssl.org/news/secadv/20230207.txt

**Comment by yuhusolutions** [comment]
The issue is inherited from alpine-linux that did not update OpenSSL libs yet.
https://github.com/alpinelinux/docker-alpine/issues/301

According to https://github.com/zulu-openjdk/zulu-openjdk/issues/134 
Once new alpine-linux docker image is updated, a new version of Zulu should pick it up and be released within a week or so.

**Comment by it-mak** [comment]
Image was updated. 
Thank you.
