### ISSUE TITLE
"latest" tags still pointing to 8u20

### ISSUE THREAD

**Issue by trask** [zulu-openjdk/zulu-openjdk#2]
```
$ docker run azul/zulu-openjdk java -version
openjdk version "1.8.0_20"
OpenJDK Runtime Environment (Zulu 8.3.0.1-linux64) (build 1.8.0_20-b26)
OpenJDK 64-Bit Server VM (Zulu 8.3.0.1-linux64) (build 25.20-b23, mixed mode)
```

I also tried debian image with same result:

```
$ docker run azul/zulu-openjdk-debian java -version
openjdk version "1.8.0_20"
OpenJDK Runtime Environment (Zulu 8.3.0.1-linux64) (build 1.8.0_20-b26)
OpenJDK 64-Bit Server VM (Zulu 8.3.0.1-linux64) (build 25.20-b23, mixed mode)
```

**Comment by patricia-dugan** [comment]
Hi Trask. 

Thanks for submitting this. The issue is fixed now. Please update your docker repo to see changes:
docker pull azul/zulu-openjdk
docker pull azul/zulu-openjdk-debian

Let us know if you have further issues or questions. Thanks again!

Patricia
Director of Community & Customer Engagement 
Twitter: @patricia_dugan
Twitter: @azulsystems
http://www.azulsystems.com

**Comment by trask** [comment]
Thanks
