### ISSUE TITLE
Zulu license

### ISSUE THREAD

**Issue by moondeck** [zulu-openjdk/zulu-openjdk#21]
Hi,
Not sure if this is the place to post this, but i am having a hard time finding the actual license of the Zulu package. Am i allowed to package Zulu for a different operating system, not currently officially supported? If yes, under what license?

Thanks!

**Comment by giltene** [comment]
Of course. Zulu is 100% free and OSS. The license is generally the same as OpenJDK. The precise license details are in the LICENSE and THIRD_PARTY_README files at the root of the jdk/jre install for versions 8 and earlier. For 11 and on, the various by-module parts of the legal subdirectory hanging of the root of the jdk/jre install contain the full license details.

Unfortunately, because the license details are quite verbose, and multiple (luckily all OSS) licenses are involved, by module, mirroring the entire OpenJDK release license structure under a single  file is impractical. And if you "think" you are looking at a single license just because some GitHub thing you've downloaded from lists just one (e.g. GPLv2+CPE) and neglects to list the whole set, you are probably wrong...

E.g. looking at the actual sources: http://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/java.xml.crypto/share/legal/santuario.md and http://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/java.base/share/legal/public_suffix.md are just two of the many many part-specific licenses involved beyond the base LICENSE file (look in all .md files in all legal subdirectories of all modules). The Zulu distro packages carefully collate all these in the locations mentioned, bundled within the ac dual bits delivered, so that they can be conveniently located and reviewed by anyone who needs/wants to look at them.
